import StoryblokProvider from "@/utils/StoryblokProvider";
import type { Metadata } from "next";
import "./globals.css";
import { SelectedFrameProvider } from "@/contexts/SelectedFrameContext";
import { Space_Grotesk } from 'next/font/google';

const typeface = Space_Grotesk({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${typeface.variable} antialiased`}>
          <SelectedFrameProvider>
            {children}
          </SelectedFrameProvider>
        </body>
      </html>
    </StoryblokProvider>
  );
}
